Repository Ribby-0254/HabitTracker, pull requests merged in 2021-03, with the labels that each got.

#24 19 create wireframe nav
  docs/WireFrame-Home-Page (1).png
Labels: documentation

#23 Create README for project
  README.md
  backend/README.md
Labels: documentation

#29 Add UML diagrams
  backend/models/customHabit.js
  backend/models/simpleHabit.js
  backend/models/user.js
Labels: documentation

#32 Revert main branch back to its original state
  backend/models/.gitkeep
  backend/models/customHabit.js
  backend/models/simpleHabit.js
  backend/models/user.js
Labels: critical issue

#33 Add UML diagrams for models
  docs/schema_diagram_v1.png
  docs/uml_diagram_v1.png
Labels: documentation

#34 Complete CONTRIBUTING.md
  docs/CONTRIBUTING.md
Labels: documentation

#36 Docker and mongodb setup
  README.md
  backend/.dockerignore
  backend/DockerFile
  backend/env/dev.env
  backend/src/boot/Bootstrap.js
  backend/src/boot/MongoDBConnection.js
  backend/src/boot/Server.js
  backend/src/index.js
  data/Dockerfile
  docker-compose.db.yml
  docker-compose.yml
  frontend/docker/.dockerignore
  frontend/docker/DockerFile
Labels: devops

#38 Creates user model and entity base class
  backend/models/.gitkeep
  backend/src/models/.gitkeep
  backend/src/models/Entity.js
  backend/src/models/User.js
Labels: backend

#39 Creates user schema and adds validator npm dependency
  backend/src/data/userSchema.js
  package-lock.json
  package.json
Labels: backend
